# -*- coding: utf-8 -*-
"""
Created on Thu Jul 28 22:36:23 2022

@author: csimo

"""
# File: ps8pr4.py
# Author: Wadner Simon, 7/31/2022
# Description: Markov Text Generation

import random

#Function 1
def create_dictionary(filename):
    """that takes a string representing the name of a text file, 
        and that returns a dictionary of key-value pairs
    """
    
    words = open(filename, 'r')
    words_text = words.read()
    words.close()
    
    words = words_text.split() #file to list of text
    

    
    d = {}
    current_word = '$'
    
    for next_word in words:
    
        if current_word not in d: #processing words
            d[current_word] = [next_word]
        else:
            d[current_word] += [next_word]
            
        
        if next_word[len(next_word)-1] in '.!?' : #checking end sentence
            next_word = '$'
            
        current_word = next_word
        
    return d
     
#Function 2 
def generate_text(word_dict, num_words):
    
    
    current_word = '$' #sentence starter
    
    for words in range(num_words):
        """that takes as parameters a dictionary of word transitions 
            (generated by the create_dictionary function) named word_dict 
            and a positive integer named num_words
        """
        word_lst = word_dict[current_word]
        next_word = random.choice(word_lst)
        
        print(next_word, end=' ') #printing on same line
        
        
        if next_word[len(next_word)-1] in '.!?': #checking end sentence
            current_word = '$' #sentence starter
            
        else:
            current_word = next_word # next sentence
            
    print()
    
        



    